### ISSUE TITLE
Interactive learning fails with missing output folders

### ISSUE THREAD

**Issue by connorbrinton** [RasaHQ/rasa#3504]
**Rasa version**: 0.14.4

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): OS X

**Issue**:
When interactive learning is done, the output path for each exported file is requested. If the file does not exist (or perhaps the folder for the file) does not exist, a `FileNotFoundError` is thrown, crashing the process. Instead, interactive learning should either:
* Allow the user to re-type the output path for the exported file
* Create all necessary folders to write to the file

```
? Do you want to stop?  Export & Quit
? Export stories to (if file exists, this will append the stories) data/core/stories.md
? Export NLU data to (if file exists, this will merge learned data with previous training examples) data/nlu/nlu.json
? Export domain file to (if file exists, this will be overwritten) domain.yml
2019-05-16 09:47:48 ERROR    rasa_core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/Users/.../.venv/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 1237, in record_messages
    _enter_user_message(sender_id, endpoint)
  File "/Users/.../.venv/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 1087, in _enter_user_message
    lambda a: not a)
  File "/Users/.../.venv/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 314, in _ask_or_abort
    should_retry = _ask_if_quit(sender_id, endpoint)
  File "/Users/.../.venv/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 588, in _ask_if_quit
    _write_data_to_file(sender_id, endpoint)
  File "/Users/.../.venv/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 566, in _write_data_to_file
    _write_stories_to_file(story_path, evts)
  File "/Users/.../.venv/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 712, in _write_stories_to_file
    with open(export_story_path, 'a', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/core/stories.md'
```

**Content of configuration file (config.yml)**:
Not relevant

**Comment by akelad** [comment]
@tabergma is this something that's fixed in master?

**Comment by tabergma** [comment]
If the file does not exists, the file is created. However, if the path itself, e.g. a directory does not exists, it will still fail. Will work on a fix.

**Comment by tabergma** [comment]
fixed via #3510
