### ISSUE TITLE
Rasa endpoints sometimes give misleading errors when authentication fails

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#6853]
**Rasa version**: 1.10.14

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: ?

**Operating system** (windows, osx, ...): ?

**Issue**: When I call the endpoints that require authentication (e.g. [`/conversations/{conversation_id}/tracker`](https://rasa.com/docs/rasa/pages/http-api#operation/getConversationTracker)), and don't authenticate as I should, **sometimes** I get the uninformative `500 Internal Server Error` response (see below). It happens when I:
- provide in the headers a valid bearer token (that gives me access to Rasa X endpoints) AND provide incorrect access token (or no token) as the `token` query parameter

It does **not** happen (and I do get a nice `401 Unauthorized` response) when I:
- provide a gibberish bearer token in the headers together with an incorrect/no token as the query parameter
- provide no bearer token together with an incorrect/no token as the query parameter

**Error (including full traceback)**:
```
<h1>Internal Server Error</h1>
<p>
	The server encountered an internal error and cannot complete
	your request.
</p>
```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by alwx** [comment]
Tried to reproduce it (current `master`, Rasa 2.0a4) but failed — so it's either me doing something wrong or this bug is already fixed in Rasa 2.0.

I started the server like that:
```
rasa run -m models --enable-api --auth-token thisismysecret --jwt-secret thisismysecret
```

And this is what happened when I tried calling `GET /status` with the correct bearer but without any `token` value. The same happens when I add any token value to request, e.g. `&token=123`

```
~ curl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiYWx3eCIsInJvbGUiOiJhZG1pbiJ9fQ.P1zMIqHTvnFYttLB0xUAf6G2W7r80K0-RiwPFJ3FlH4" http://localhost:5005/status

{"model_file":"models\/20201007-140921.tar.gz","fingerprint":{"config":"99914b932bd37a50b983c5e7c90ae93b","core-config":"56f4adf827a73481c28601d7d6c62562","nlu-config":"9cd58a3ec816e17b8f149091ba14dbf6","domain":283583868163721262,"nlg":"ea3547fc103c9b05992f407b431f4f0f","project":null,"messages":1955115866797235455,"stories":750931222862006648,"trained_at":1602072561.726249,"version":"2.0.0rc4"},"num_active_training_jobs":0}%
```

**Comment by alwx** [comment]
@samsucik could you please check and update me if it's still valid?

**Comment by samsucik** [comment]
@alwx I can still get the same behaviour. Try querying our instance in case you're not doing it already: `https://website-demo.rasa.com/core/conversations/588388052f2b41c9957288472363b987/tracker` (+ the query param `token` and/or the bearer token in the headers).

**Comment by alwx** [comment]
Yes, but `https://website-demo.rasa.com` instance runs Rasa 1.10.4, and I did my attempts to reproduce it with Rasa 2.0 (current `master`).
I am not sure if the bugfix should be backported to 1.x because we're about to release 2.0. What do you think?

**Comment by samsucik** [comment]
Fair enough. In all honesty, I don't know. In a sense, I'm just a user of our instance. And now that I know how to authenticate properly this doesn't affect me personally anymore.
