### ISSUE TITLE
Faceing issues installing rasa due to package cryptography

### ISSUE THREAD

**Issue by adithyaan-creator** [RasaHQ/rasa#7713]
OS = windows
python3
pip == 19.2.3

Error : failed building wheel for cryptography

Any workarounds?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment]
@adithyaan-creator I believe this was fixed with the release of [Rasa Open Source 2.2.5](https://github.com/RasaHQ/rasa/actions/runs/481246779) last night

**Comment by adithyaan-creator** [comment]
@TyDunn I am still facing the same issue. 
Could the OS be the issue? I am using windows.

**Comment by TyDunn** [comment]
@adithyaan-creator Hmm. Can you provide the full error message? Are you installing in a brand new virtual environment?

**Comment by adithyaan-creator** [comment]
@TyDunn It works well now. Thanks for that.
But when doing rasa train, getting the following error.

AttributeError: module 'sip' has no attribute 'setapi'

**Comment by TyDunn** [comment]
@adithyaan-creator It looks like you need to install `matplotlib`. This should have already happened though 🤔

**Comment by TyDunn** [comment]
@adithyaan-creator Maybe it has [something to do with matplotlib](https://stackoverflow.com/questions/64291087/matplotlib-module-sip-has-no-attribute-setapi)? `rasa train` should just work after you install though 🤔

**Comment by TyDunn** [comment]
Closing this issue. Please reopen if you are still facing this problem

**Comment by DishaVaish** [comment]
i am also facing same error .how to fix it

**Comment by DishaVaish** [comment]
@TyDunn  how to fix it

**Comment by TyDunn** [comment]
@DishaVaish I'm working on https://github.com/continuedev/continue these days, but I would make sure you have followed all of the steps to [set up your environment](https://rasa.com/docs/rasa/installation/environment-set-up) and [install Rasa Open Source](https://rasa.com/docs/rasa/installation/installing-rasa-open-source). 

If you still run into this error, then I would open a new issue with a lot more details (operating system, Rasa version, etc). It's very unlikely your issue is the same as the one from three years ago. Hope this helps :)
